version: '3.9'
services:
  api:
    build: .
    container_name: quadlingo-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/app  # hot reload для dev

  postgres:
    image: postgres:16
    container_name: quadlingo-postgres
    environment:
      POSTGRES_DB: quadlingo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7983
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: quadlingo-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  postgres_data: